limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;
limit_req_zone $binary_remote_addr zone=general:10m rate=30r/s;
limit_req_zone $binary_remote_addr zone=register:10m rate=3r/m;

map $http_origin $allowed_origin {
    default "";
    "https://xxxxxxx.com" $http_origin;
    "https://www.xxxxxxx.com" $http_origin;
}

server {
    listen 443 ssl;
    server_name xxxxxxx.com www.xxxxxxx.com;
    ssl_certificate /etc/ssl/fullchain.pem;
    ssl_certificate_key /etc/ssl/key.pem;

    # Static web assets
    location / {
        limit_req zone=general burst=20 nodelay;
        add_header 'Access-Control-Allow-Origin' $allowed_origin always;
        add_header 'Referrer-Policy' 'strict-origin-when-cross-origin';
        add_header 'X-Content-Type-Options' 'nosniff';
        add_header 'X-Frame-Options' 'DENY';
        add_header 'Strict-Transport-Security' 'max-age=31536000; includeSubDomains; preload';
        add_header 'Content-Security-Policy' "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; script-src 'self' 'sha256-BdF4U9TryPli2gOXArKmjs3toymMQM6Cuf+/M4wr96s=' 'sha256-NWj1JLkgulwqfqdvu1nr0B8woaRTc0zJLjnH1Cq3HgI=';";
        root /var/www/html;
        index index.html;
    }

    # API
    location /api/v1/ {
        limit_req zone=api burst=20 nodelay;
        proxy_pass http://api:8000/api/v1/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Registration endpoint
    location /register {
        limit_req zone=register burst=2 nodelay;

        add_header 'Access-Control-Allow-Origin' $allowed_origin always;
        add_header 'Access-Control-Allow-Methods' 'POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Content-Type';

        proxy_pass http://register:8001/register;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}

server {
    listen 80;
    server_name xxxxxxx.com www.xxxxxxx.com;
    return 301 https://$host$request_uri;
}
