#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $SQL_SVIX_USER WITH PASSWORD '$SQL_SVIX_PASSWORD';
    CREATE DATABASE $SQL_SVIX_DB;
    GRANT ALL PRIVILEGES ON DATABASE $SQL_SVIX_DB TO $SQL_SVIX_USER;
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$SQL_SVIX_DB" <<-EOSQL
    GRANT ALL ON SCHEMA public TO $SQL_SVIX_USER;
    ALTER SCHEMA public OWNER TO $SQL_SVIX_USER;
EOSQL
